[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-args=-lcrypto -lws2_32 -lgdi32 -lcrypt32 -ladvapi32 -lntdll -luser32 -lkernel32 -lmingwex -lmingw32 -lgcc -lmsvcrt"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-args=-lcrypto -lc"]
